project_tracker/movieblog/urls.py
from django.urls import path, re_path
from movieblog import views

from django.contrib.sitemaps.views import sitemap

from movieblog.sitemap import FilmSitemap, CategorySitemap

sitemaps = {
    'FilmSitemap': FilmSitemap,
    'CategorySitemap': CategorySitemap,
}

app_name = 'movieblog'
urlpatterns = [
    path('search/', views.SearchPageView.as_view(), name='search_page'),
    path('remove_from_list/', views.RemoveFromListView.as_view(), name='remove_from_list'),
    path('add_to_list/', views.AddToListView.as_view(), name='add_to_list'),
    path("rate_movie/", views.RateMovie, name="rate_movie"),
    path('<int:pk>-<str:slug>/', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>-<str:slug>/', views.CategoryPageView.as_view(), name='category_page'),
    path('film/<int:pk>-<str:slug>/', views.FilmPageView.as_view(), name='film_page'),
    re_path(r'/(?P<tag_name>[\w-]+)/$', views.TagPageView.as_view(), name='tag_page'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("comment/add/<int:pk>/", views.AddCommentView.as_view(), name="add_comment"),  
    path("comment/edit/<int:pk>/", views.EditCommentView.as_view(), name="edit_comment"),  
    path("comment/delete/<int:pk>/", views.DeleteCommentView.as_view(), name="delete_comment"),
]

project_tracker/project_tracker/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
 
 


urlpatterns = [
    path("admin/", admin.site.urls),
    path('movieblog/', include('movieblog.urls', namespace='movieblog')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path('user/', include('user_app.urls', namespace='user_app')),
     
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = "utils_app.exception_handlers.bad_request_handler"  
handler403 = "utils_app.exception_handlers.permission_denied_handler"  
handler404 = "utils_app.exception_handlers.page_not_found_handler"  
handler500 = "utils_app.exception_handlers.server_error_handler"

project_tracker/user_app/urls.py
from django.urls import path  

from user_app import views  
from django.contrib.auth import views as auth_views  
from django.urls import reverse_lazy

app_name = 'user_app'  
urlpatterns = [  
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user_app/logout.html'), name='logout'), 
    path('signup/', views.CustomRegistrationView.as_view(), name='signup'), 
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),  
    path('password_reset_confirm/<uidb64>/<token>/', views.CustomUserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),  
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='user_app/password_reset_complete.html'), name='password_reset_complete'),  
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user_app/password_reset_done.html'), name='password_reset_done'),
    path('<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('<str:username>/settings/', views.UserSettingsView.as_view(), name='user_profile_settings'),
  
]

project_tracker/movieblog/forms.py
from django import forms
from .models import UserFilmList
from .models import CommentModel

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100,
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control me-2 mx-1',
                                    'placeholder': 'Что ищем?',
                                }
                            ))

    def clean_query(self):
        query = self.cleaned_data['query']
        cleaned_query = " ".join(query.split())
        return cleaned_query
    
class CommentForm(forms.ModelForm):  
    content = forms.CharField(  
        widget=forms.Textarea(  
            attrs={  
                "class": "form-text",  
                "placeholder": "Введите текст комментария",  
                "rows": 5  
            }  
        ),  
    )  

    class Meta:  
        model = CommentModel  
        fields = ("content",)

class UserFilmListForm(forms.ModelForm):
    class Meta:
        model = UserFilmList
        fields = ['film', 'list_type']

project_tracker/movieblog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import CategoryModel, FilmModel, CommentModel, RateModel, UserFilmList
from django.views.generic import TemplateView
from django.views import View
from django.core.paginator import Paginator
from movieblog import models, forms
from django.db.models import Q
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from .forms import CommentForm, UserFilmListForm
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect
import json
from django.http import JsonResponse


class IndexView(View):
    template_name = 'movieblog/index.html'

    def get(self, request, pk, slug):
        category = CategoryModel.objects.get(pk=pk)
        descendant_categories = category.get_descendants(include_self=True)
        films = FilmModel.objects.filter(category__in=descendant_categories)

        context = {
            'category': category,
            'films': films,
        }
        return render(request, self.template_name, context)

class CategoryPageView(View):
    template_name = 'movieblog/category_page.html'

    def get(self, request, pk, slug):
        if not request.user.is_authenticated:
            return redirect(reverse('user_app:login'))
        category = CategoryModel.objects.get(pk=pk)
        films = FilmModel.objects.filter(category=category)

        user_film_lists = UserFilmList.objects.filter(user=request.user, list_type=slug)
        films = [user_film_list.film for user_film_list in user_film_lists]

        context = {
            'category': category,
            'films': films,
        }
        return render(request, self.template_name, context)
    
class FilmPageView(DetailView):
    model = FilmModel
    template_name = 'movieblog/film_page.html'
    context_object_name = 'film'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.views += 1
        self.object.save()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['comments'] = CommentModel.objects.filter(film=self.object)

        rating = None
        try:
            if self.request.user.is_authenticated:
                rating = RateModel.objects.get(movie=self.object, user=self.request.user)
        except RateModel.DoesNotExist:
            rating = None
        context['rating'] = rating

        return context
    
class TagPageView(View):
    template_name = 'movieblog/tag_page.html'

    def get(self, request, tag_name):
        films_list = FilmModel.objects.filter(tags__slug=tag_name).distinct()

        paginator = Paginator(films_list, 10)
        page_number = request.GET.get('page', 1)
        films = paginator.page(page_number)

        context = {
            'tag_name': tag_name,
            'films': films
        }
        return render(request, self.template_name, context)
       
class SearchPageView(TemplateView):
    template_name = 'movieblog/search_page.html'

    def get(self, request, *args, **kwargs):
        form = forms.SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            results = models.FilmModel.film_manager.filter(Q(full_body__icontains=query) | Q(title__icontains=query))


            paginator = Paginator(results, 10)
            page_number = request.GET.get('page', 1)
            results = paginator.get_page(page_number)

            context = {"query": query,
                       "results": results,
                       'user' : request.user,}

            return render(request,
                          self.template_name,
                          context)

        return render(request,
                      self.template_name,
                      {"query": request.GET['query']})

class BaseCommentView:  
    model = CommentModel  

    def get_success_url(self):  
        film = FilmModel.objects.get(pk=self.object.film.pk)  
        return reverse(  
            "movieblog:film_page",  
            kwargs={"pk": film.pk, "slug": film.slug},  
        )
    
class AddCommentView(BaseCommentView, CreateView):  
    form_class = CommentForm  
    template_name = "movieblog/comments.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.film = FilmModel.objects.get(pk=self.kwargs.get("pk"))
        parent_id = self.request.POST.get('parent_id')
        reply_to = self.request.POST.get('reply_to')

        if parent_id:
            form.instance.parent = CommentModel.objects.get(id=parent_id)

        if reply_to:
            form.instance.content = f"@{reply_to} {form.instance.content}"

        return super().form_valid(form)
    
class EditCommentView(BaseCommentView, UpdateView):  
    form_class = CommentForm  
    model = CommentModel 
    template_name = 'movieblog/comment_edit.html'
    context_object_name = 'comment'

    def get_success_url(self):
        comment = self.get_object()
        return reverse_lazy('movieblog:film_page', kwargs={'pk': comment.film.pk, 'slug': comment.film.slug})

class DeleteCommentView(BaseCommentView, DeleteView):  
    template_name = "movieblog/comment_delete.html"
    def get_success_url(self):
        comment = self.get_object()
        return reverse_lazy('movieblog:film_page', kwargs={'pk': comment.film.pk, 'slug': comment.film.slug})
    


def update_rating(movie_id):
    movie = get_object_or_404(FilmModel, pk=movie_id)
    ratings = RateModel.objects.filter(movie=movie)
    sum_rating = 0
    count_rating = 0
    for rating in ratings:
        sum_rating += rating.rate_number
        count_rating += 1
    print(sum_rating)
    if count_rating != 0:
        movie.rating = sum_rating / count_rating
    else:
        movie.rating = 0
    movie.save()
    return movie.rating
    

@require_http_methods(['POST'])
@csrf_protect
def RateMovie(request):
    if not request.user.is_authenticated:
        return JsonResponse({'error': 'Not authenticated'}, status=401)
    user = request.user

    body_request = json.loads(request.body)
    movie_id = body_request['movie_id']
    rate_number = body_request['rate_number']

    movie = get_object_or_404(FilmModel, pk=movie_id)

    body_response = {}

    try:
        rate = RateModel.objects.get(user=user, movie=movie)
        if(rate.rate_number == int(rate_number)):
            rate.delete()
        else:
            rate.rate_number = rate_number
            rate.save()
    except:
        rate = RateModel.objects.create(user=user, movie=movie, rate_number=rate_number)

    body_response['movie_rating'] = update_rating(movie_id)
    return JsonResponse(body_response)


class AddToListView(View):
    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('login')

        form = UserFilmListForm(request.POST)
        if form.is_valid():
            user_film_list = form.save(commit=False)
            user_film_list.user = request.user
            try:
                user_film_list.save()
                return redirect('movieblog:film_page', pk=user_film_list.film.pk, slug=user_film_list.film.slug)
            except:
                form.add_error(None, "Этот фильм уже добавлен в этот список.")

        return render(request, 'movieblog/add_to_list.html', {'form': form})


class RemoveFromListView(View):
    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('user_app:login')

        film_id = request.POST.get('film_id')
        list_type = request.POST.get('list_type')

        user_film_list = get_object_or_404(UserFilmList, user=request.user, film_id=film_id, list_type=list_type)
        user_film_list.delete()

        return redirect('movieblog:category_page', pk=user_film_list.film.category.pk, slug=list_type)

project_tracker/movieblog/templates/movieblog/add_to_list.html
{% extends "movieblog/base.html" %}

{% block content %}
  <h2>Добавить фильм в список</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
  </form>
{% endblock %}

project_tracker/movieblog/templates/movieblog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href={% static "css/styles.css" %} />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body class="dark-theme">
    {% include 'movieblog/nav.html' %}
    <main>
        <div class="top">
            <div class="search">
                <form method="GET" action="{% url 'movieblog:search_page' %}" class="search-line">
                    <div class="search-item">
                        {{ search_form.query }}
                    </div>
                    <button class="btn search-link link-border" type="submit">Поиск</button>
                </form>
            </div>
            <div class="entrance">
                {% if not user.is_authenticated %}
                    <a href="{% url 'user_app:signup' %}" class="entrance__link link link-item"> регистрация </a>
                    <a href="{% url 'user_app:login' %}" class="entrance__link link link-item"> вход </a>
                {% else %}
                    <form id="logout-form" action="{% url 'user_app:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn-logout">
                            <span class="entrance__link link link-item">выход</span>
                        </button>
                    </form>
                    <a href="{% url 'user_app:user_profile' username=user.username %} " class="entrance__link link link-item navbar__item">{{user.username}}</a>
                {% endif %}

            </div>
        </div>

    {% block content %}{% endblock content %}
    </main>

    <script src={% static "js/script.js" %} ></script>
</body>
</html>

project_tracker/movieblog/templates/movieblog/category_page.html
{% extends "movieblog/base.html" %} 

{% block content %}
        <div class="content">
            <div class="title">
                <h1>{{ category.title }}</h1>
            </div>
            <div class="movies">
                {% for film in films %}
                    <div class="category-movie">
                        <a href="{{ film.get_absolute_url }}" class="movie-item">
                            <img src="{{ film.image.url }}" alt="" class="movie-image">
                        </a>
                        <div class="minus-block">
                            <form method="post" action="{% url 'movieblog:remove_from_list' %}">
                                {% csrf_token %}
                                <input type="hidden" name="film_id" value="{{ film.id }}">
                                <input type="hidden" name="list_type" value="{{ category.slug }}">
                                <button type="submit" class="minus">-</button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

{% endblock content %}

project_tracker/movieblog/templates/movieblog/comment_delete.html
{% extends 'movieblog/base.html' %}
{% block title %}Удаление комментария{% endblock %}

{% block content %}
    <div class="movie-content">
        <div >
            <div class="title">Удаление комментария</div>
            <p class="title">Вы действительно хотите удалить этот комментарий?</p>
            <pre>{{ object.comment }}</pre>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-success" type="submit">Да, удалить</button>
                <a href="{% url 'movieblog:film_page' pk=object.film.pk slug=object.film.slug %}"
                class="link-comment">Отмена</a>
            </form>
        </div>
    </div>
{% endblock %}

project_tracker/movieblog/templates/movieblog/comments.html
  {% if comments %}
        {% for comment in comments %}
            <div class="review-item">
                <div class="review-top">
                    <div class="person">
                        <img class="image-avatar" src="{{ comment.user.profile.user_avatar.url }}" alt="{{ comment.user.username }}">
                        Пользователь: &nbsp;<a href="{% url 'user_app:user_profile' username=comment.user.username %}" class="link link-item">{{ comment.user }}</a>
                    </div>
                </div>
                <div class="review-content">
                    <span class="description"> 
                        {{ comment.content }} 
                        <br>
                        | {{ comment.created_at }} | {% if comment.user == user or user.is_superuser %}
                        <a href="{% url 'movieblog:edit_comment' pk=comment.pk %}" class="link-comment">Редактировать</a> |
                        <a href="{% url 'movieblog:delete_comment' pk=comment.pk %}" class="link-comment">Удалить</a>
                        {% endif %}
                    </span>
                </div>
                <hr class="line-review">
    
                {% if user.is_authenticated %}
                    <button class="btn btn-outline-primary comment-review" type="button" onclick="showReplyForm('{{ comment.id }}', '{{ comment.user.username }}')">Ответить</button>
                    <div id="reply-form-{{ comment.id }}" style="display:none; margin-top: 10px;">
                        <form method="post" enctype="multipart/form-data" action="{% url 'movieblog:add_comment' pk=film.pk %}">
                            {% csrf_token %}
                            {{ comment_form.content }}
                            <input type="hidden" name="parent_id" value="{{ comment.id }}">
                            <input type="hidden" name="reply_to" value="{{ comment.user.username }}">
                            <button class="btn btn-outline-primary mt-1" type="submit">Отправить</button>
                        </form>
                    </div>
                {% endif %}
    
                {% if comment.children.all %}
                    <button class="btn btn-outline-secondary mt-1" type="button" onclick="toggleChildren('{{ comment.id }}')">Свернуть/Развернуть ответы</button>
                    <div id="children-{{ comment.id }}" style="margin-left: 20px;">
                        {% for child in comment.children.all %}
                            <div class="children-answer" id="comment-{{ child.id }}">
                                <div class="person">
                                    <img class="image-avatar" src="{{ child.user.profile.user_avatar.url }}" alt="{{ child.user.username }}">
                                    <a href="{% url 'user_app:user_profile' username=child.user.username %}" class="link-item description">{{ child.user }}</a>
                                </div>
                                <span class="description">{{ child.content }}</span><br>
                                <span class="description">
                                    | {{ child.created_at }} | {% if child.user == user or user.is_superuser %}
                                        <a href="{% url 'movieblog:edit_comment' pk=child.pk %}" class="link-comment">
                                            Редактировать</a> |
                                    <a href="{% url 'movieblog:delete_comment' pk=child.pk %}" class="link-comment">Удалить</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    {% endfor %}
{% else %}
    <p class="review-item">Нет отзывов</p>
{% endif %}

<span class="movie-title">Добавить отзыв:</span>
{% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data" action="{% url 'movieblog:add_comment' pk=film.pk %}">
        {% csrf_token %}
        <div class="form-group">
            {{ comment_form.content }}
        </div>
        <button class="btn btn-success" type="submit">Отправить</button>
    </form>
{% else %}
    <p><a href="{% url 'user_app:login' %}" class="entrance__link link link-item">Войдите</a> чтобы добавить комментарий.</p>
{% endif %}

project_tracker/movieblog/templates/movieblog/film_page.html
{% extends "movieblog/base.html" %} 

{% block content %}
        <div class="movie-content">
            <div class="movie-block">
                <div class="movie-block__top">
                    <div class="movie-title">
                        {{ film.title }}
                    </div>
                    <div class="wishlist-button">
                        {% comment %} <button class="btn btn-wishlist" data-movie-id={{film.id}} id="wishlist">
                            <svg width="1rem" height="1rem" viewbox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M19 19.2674V7.84496C19 5.64147 17.4253 3.74489 15.2391 3.31522C13.1006 2.89493 10.8994 2.89493 8.76089 3.31522C6.57467 3.74489 5 5.64147 5 7.84496V19.2674C5 20.6038 6.46752 21.4355 7.63416 20.7604L10.8211 18.9159C11.5492 18.4945 12.4508 18.4945 13.1789 18.9159L16.3658 20.7604C17.5325 21.4355 19 20.6038 19 19.2674Z" stroke="#363853" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                            Add to wishlist
                        </button> {% endcomment %}
                        <form action="{% url 'movieblog:add_to_list' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="film" value="{{ film.id }}">
                            <select class="btn search-link border" name="list_type">
                                <option value="budu-smotret">Желаемое</option>
                                <option value="posmotreno">Просмотренное</option>
                                <option value="izbrannoe">Избранное</option>
                            </select>
                            <button class="btn search-link link-border" type="submit">Добавить в список</button>
                        </form>
                    </div>
                </div>
                <div class="movie-block__main">
                    <div class="movie-left">
                        <a href="#" class="movie-item">
                            <img src="{{ film.image.url }}" alt="" class="movie-image">
                        </a>
                    </div>
                    <div class="movie-right">
                        <div class="movie-tags">
                            {% for tag in film.tags.all %}
                                <a href="{% url 'movieblog:tag_page' tag.slug %}" class="tag-item">
                                    <span>{{ tag.name }}</span>
                                </a>
                            {% endfor %}
                        </div>
                        <div>
                            <span class="description">
                                {{ film.full_body | safe }}
                            </span>
                        </div>
                        <div class="movie-rating">
                            {% if film.rating == "0" %}
                                <span class="rating">Рейтинг: Слишком мало оценок</span>
                            {% else %}
                                <span class="rating">Рейтинг: <span class="">{{film.rating}}</span>/5</span>
                            {% endif %}
                        </div>
                        <div class="ranks">
                            <button class="ranks__mark {% if rating.rate_number == 1 %}active-mark{% endif %}" id="toggle-mark" data-rate-number="1" data-movie-id={{film.id}}>
                                <span>1</span>
                            </button>
                            <button class="ranks__mark {% if rating.rate_number == 2 %}active-mark{% endif %}" id="toggle-mark" data-rate-number="2" data-movie-id={{film.id}}>
                                <span>2</span>
                            </button>
                            <button class="ranks__mark {% if rating.rate_number == 3 %}active-mark{% endif %}" id="toggle-mark" data-rate-number="3" data-movie-id={{film.id}}>
                                <span>3</span>
                            </button>
                            <button class="ranks__mark {% if rating.rate_number == 4 %}active-mark{% endif %}" id="toggle-mark" data-rate-number="4" data-movie-id={{film.id}}>
                                <span>4</span>
                            </button>
                            <button class="ranks__mark {% if rating.rate_number == 5 %}active-mark{% endif %}" id="toggle-mark" data-rate-number="5" data-movie-id={{film.id}}>
                                <span>5</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>



            <iframe width="560" height="315" src="{{film.link_to_player}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

            <div class="reviews">
                <div class="movie-title">
                    Отзывы:
                </div>
                {% include "movieblog/comments.html" with film=film comments=comments %}
        </div>
{% endblock content %}

project_tracker/movieblog/templates/movieblog/reply_form.html
<!-- movieblog/templates/movieblog/reply_form.html -->
{% if user.is_authenticated %}
<button class="btn btn-outline-primary mt-1" type="button" onclick="showReplyForm('{{ comment.id }}', '{{ comment.user.username }}')">Ответить</button>
<div id="reply-form-{{ comment.id }}" style="display:none; margin-top: 10px;">
    <form method="post" enctype="multipart/form-data" action="{% url 'movieblog:add_comment' pk=film.pk %}">
        {% csrf_token %}
        {{ comment_form.content }}
        <input type="hidden" name="parent_id" value="{{ comment.id }}">
        <input type="hidden" name="reply_to" value="{{ comment.user.username }}">
        <button class="btn btn-outline-primary mt-1" type="submit">Отправить</button>
    </form>
</div>
{% endif %}

project_tracker/movieblog/templates/movieblog/search_page.html
{% extends "movieblog/base.html" %}
{% block title %}{{ query }}{% endblock %}
    {% block content %}
    <div class="content">
        <section class="info">
            <div class="container">
                <h1>Результаты по запросу: {{ query }}</h1>
                <hr>        </div>    </section>
        <section class="films">
            {% if results %}
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9 col-sm-12 cat-block">
                            {% for film in results %}
                                <div class="row-search">
                                    <div class="movie-item">
                                        <a href="{{ film.get_absolute_url }}">
                                            <img src="{{ film.image.url }}" alt="{{ film.title }}" class="movie-image">
                                        </a>
                                    </div>                                
                                    <div class="movie-se">
                                        <p class="movie-title">{{ film.title }}</p>
                                            <p class="description"><a
                                                    href="{{ film.category.get_absolute_url }}" class="link-comment">{{ film.category }}</a>
                                                | {{ film.director }} | {{ film.publish | date:"d F Y" }} |
                                                Просмотров: {{ film.views }}</p>
                                            {% for tag in film.tags.all %}
                                                <a href="{% url 'movieblog:tag_page' tag.slug %}" class="link-comment">{{ tag.name }}</a>
                                            {% endfor %}
                                        {{ film.short_body | safe }}
                                    </div>
                                </div>                            <hr class="m-3">
                            {% endfor %}
                        </div>

                </div>        {% else %}
                <div class="container">
                    <h3>Нет результатов</h3>
                </div>        {% endif %}
        </section>
    </div>
    {% endblock %}