project_tracker/project_tracker/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
 
 


urlpatterns = [
    path("admin/", admin.site.urls),
    path('movieblog/', include('movieblog.urls', namespace='movieblog')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path('user/', include('user_app.urls', namespace='user_app')),
     
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = "utils_app.exception_handlers.bad_request_handler"  
handler403 = "utils_app.exception_handlers.permission_denied_handler"  
handler404 = "utils_app.exception_handlers.page_not_found_handler"  
handler500 = "utils_app.exception_handlers.server_error_handler"

project_tracker/user_app/urls.py
from django.urls import path  

from user_app import views  
from django.contrib.auth import views as auth_views  
from django.urls import reverse_lazy

app_name = 'user_app'  
urlpatterns = [  
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user_app/logout.html'), name='logout'), 
    path('signup/', views.CustomRegistrationView.as_view(), name='signup'), 
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),  
    path('password_reset_confirm/<uidb64>/<token>/', views.CustomUserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),  
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='user_app/password_reset_complete.html'), name='password_reset_complete'),  
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user_app/password_reset_done.html'), name='password_reset_done'),
    path('<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('<str:username>/settings/', views.UserSettingsView.as_view(), name='user_profile_settings'),
  
]

project_tracker/user_app/models.py
from django.db import models
from datetime import datetime  
from urllib import request  
from PIL import Image  
from django.contrib.auth.models import User  
from django.db import models  
import os
from django.core.files import File
from django.conf import settings

class ProfileModel(models.Model):  
    class Genders(models.TextChoices):  
        UNDEFINED = 'U', 'не выбран'  
        MALE = 'M', 'мужской'  
        FEMALE = 'F', 'женский'  

    user = models.OneToOneField(User,  
                                on_delete=models.CASCADE,  
                                related_name='profile',  
                                verbose_name='Пользователь')  
    
    gender = models.CharField(max_length=1,  
                              choices=Genders.choices,  
                              default=Genders.UNDEFINED,  
                              verbose_name='Пол')  
    dob = models.DateField(blank=True,  
                           null=True,  
                           verbose_name='Дата рождения')  
    user_avatar = models.ImageField(upload_to='user/avatars/',  
                                    blank=True,  
                                    null=True,  
                                    verbose_name='Аватар пользователя')  

    show_email = models.BooleanField(default=False,  
                                     verbose_name='Отображать Email?')  
    show_last_name = models.BooleanField(default=False,  
                                         verbose_name='Отображать фамилию?')  
    
    class Meta:  
        verbose_name = 'Профиль'  
        verbose_name_plural = 'Профили'  

    def save(self, *args, **kwargs):  
        if not self.user_avatar:  
            default_image_path = os.path.join(settings.MEDIA_ROOT, 'film', '2024', '06', 'default_avatar.png')
            with open(default_image_path, 'rb') as f:
                self.user_avatar.save(f'{self.user.username}.png', File(f), save=False)
        
        super().save(*args, **kwargs)  

        img = Image.open(self.user_avatar.path)  

        if img.height > 300 or img.width > 300:  
            output_size = (300, 300)  
            img.thumbnail(output_size)  
            img.save(self.user_avatar.path)  
            
    def get_age(self):  
        if self.dob:  
            today = datetime.today()  
            age = today.year - self.dob.year  

            if today.month < self.dob.month:  
                age -= 1  
            elif today.month > self.dob.month and today.day < self.dob.day:  
                age -= 1  

            return age  

    def __str__(self):  
        return self.user.username

project_tracker/user_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation  
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, PasswordChangeForm
from movieblog import models
from user_app.models import ProfileModel

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        label='Имя пользователя',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите имя пользователя'
        })
    )
    password = forms.CharField(
        max_length=128,
        label='Пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })
    )

    class Meta:
        model = User
        fields = ['username', 'password']


class RegistrationForm(UserCreationForm):  
    username = forms.CharField(  
        max_length=150,  
        label='Имя пользователя',  
        widget=forms.TextInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите имя пользователя'  
        })  
    )  
    email = forms.EmailField(  
        widget=forms.EmailInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите email'  
        })  
    )  
    password1 = forms.CharField(  
        max_length=128,  
        label='Пароль',  
        widget=forms.PasswordInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите пароль'  
        })  
    )  
    password2 = forms.CharField(  
        max_length=128,  
        label='Подтверждение пароля',  
        widget=forms.PasswordInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Повторите пароль'  
        })  
    )  

    class Meta:  
        model = User  
        fields = ['username', 'email', 'password1', 'password2', ]

from django.contrib.auth import password_validation  
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm


class CustomPasswordResetForm(PasswordResetForm):  
    email = forms.EmailField(  
        label="Email",  
        max_length=254,  
        widget=forms.EmailInput(  
            attrs={'class': 'form-control',  
                   'placeholder': 'Введите Email',  
                   "autocomplete": "email"}  
        )  
    )  


class CustomSetPasswordForm(SetPasswordForm):  
    error_messages = {  
        "password_mismatch": "Пароли не совпадают"  
    }  
    new_password1 = forms.CharField(  
        label='Новый пароль',  
        widget=forms.PasswordInput(  
            attrs={'class': 'form-control',  
                   'placeholder': 'Введите новый пароль',  
                   "autocomplete": "new-password"}  
        ),  
        strip=False,  
        help_text=password_validation.password_validators_help_text_html(),  
    )  
    new_password2 = forms.CharField(  
        label='Подтверждение нового пароля',  
        strip=False,  
        widget=forms.PasswordInput(  
            attrs={'class': 'form-control',  
                   'placeholder': 'Подтвердите новый пароль',  
                   "autocomplete": "new-password"}  
        ),  
    )
    
class UserInfoForm(forms.ModelForm):  
    username = forms.CharField(  
        max_length=150,  
        label='Имя пользователя (username)',  
        widget=forms.TextInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите имя пользователя'  
        })  
    )  
    email = forms.EmailField(  
        widget=forms.EmailInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите email'  
        })  
    )  
    first_name = forms.CharField(  
        max_length=150,  
        label='Имя',  
        required=False,  
        widget=forms.TextInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите ваше имя'  
        })  
    )  
    last_name = forms.CharField(  
        max_length=150,  
        label='Фамилия',  
        required=False,  
        widget=forms.TextInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите вашу фамилию'  
        })  
    )  

    class Meta:  
        model = User  
        fields = ['username', 'email', 'first_name', 'last_name']
class UserPasswordForm(PasswordChangeForm):  
    old_password = forms.CharField(  
        max_length=128,  
        label='Старый пароль',  
        widget=forms.PasswordInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите старый пароль'  
        })  
    )  
    new_password1 = forms.CharField(  
        max_length=128,  
        label='Новый пароль',  
        help_text=password_validation.password_validators_help_text_html(),  
        widget=forms.PasswordInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Введите новый пароль'  
        })  
    )  
    new_password2 = forms.CharField(  
        max_length=128,  
        label='Подтверждение нового пароля',  
        widget=forms.PasswordInput(attrs={  
            'class': 'form-control',  
            'placeholder': 'Повторите новый пароль'  
        })  
    )

class ProfileForm(forms.ModelForm):  
    gender = forms.ChoiceField(  
        label='Пол',  
        choices=ProfileModel.Genders.choices,  
        required=False,  
        widget=forms.Select(  
            attrs={  
                'class': 'form-select',  
            }  
        )  
    )  
    dob = forms.DateField(  
        label='Дата рождения',  
        required=False,  
        widget=forms.DateInput(  
            format='%Y-%m-%d',  
            attrs={  
                'type': 'date',  
                'class': 'form-control',  
            }  
        )  
    )  

  
    user_avatar = forms.FileField(  
        label='Аватарка',  
        required=False,  
        widget=forms.FileInput(  
            attrs={  
                'type': 'file',  
                'class': 'form-control',  
            }  
        )  
    )  

    show_last_name = forms.BooleanField(  
        required=False,  
        widget=forms.CheckboxInput(  
            attrs={  
                'class': 'form-check-input mt-0',  
            }  
        )  
    )  
    show_email = forms.BooleanField(  
        required=False,  
        widget=forms.CheckboxInput(  
            attrs={  
                'class': 'form-check-input mt-0',  
            }  
        )  
    )  
    

    class Meta:  
        model = ProfileModel  
        fields = ['gender', 'dob', 'user_avatar', 'show_last_name', 'show_email']

project_tracker/user_app/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from user_app.forms import LoginForm, RegistrationForm
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import TemplateView
from user_app.forms import UserInfoForm, UserPasswordForm, ProfileForm 
from movieblog import forms

class CustomLoginView(LoginView):
    authentication_form = LoginForm
    template_name = 'user_app/login.html'
    extra_context = {'title': 'Авторизация на сайте'}

    def get_success_url(self):
        return reverse_lazy('movieblog:index', kwargs={'pk': 18, 'slug': 'vse-filmy'})

class CustomRegistrationView(CreateView):  
    form_class = RegistrationForm  
    template_name = 'user_app/signup.html'  
    extra_context = {'title': 'Регистрация на сайте'}  

    def get_success_url(self):  
        return reverse_lazy('user_app:login')  

    def form_valid(self, form):  
        user = form.save()  
        return super().form_valid(form)
    
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from user_app.forms import CustomPasswordResetForm, CustomSetPasswordForm


class CustomPasswordResetView(PasswordResetView):  
    template_name = 'user_app/password_reset.html'  
    email_template_name = 'user_app/password_reset_email.html'  
    form_class = CustomPasswordResetForm  
    success_url = reverse_lazy('user_app:password_reset_done')  


class CustomUserPasswordResetConfirmView(PasswordResetConfirmView):  
    template_name = 'user_app/password_reset_confirm.html'  
    success_url = reverse_lazy('user_app:password_reset_complete')  
    form_class = CustomSetPasswordForm

class UserProfileView(TemplateView):  
    template_name = 'user_app/profile_page.html'  

    def get_context_data(self, **kwargs):  
        context = super().get_context_data(**kwargs)  
        try:  
            user = get_object_or_404(User, username=self.kwargs.get('username'))  
        except User.DoesNotExist:  
            raise Http404("Пользователь не найден")  
        context['user_profile'] = user   
        context['title'] = f'Профиль пользователя {user}'  
        return context
    
class UserSettingsView(LoginRequiredMixin, TemplateView):  
    template_name = 'user_app/profile_settings_page.html'  

    def dispatch(self, request, *args, **kwargs):  
        if request.user == get_object_or_404(User, username=self.kwargs.get('username')):  
            return super().dispatch(request, *args, **kwargs)  
        else:  
            raise HttpResponseForbidden("Вы не имеете доступа к этой странице.")  

    def get_context_data(self, **kwargs):  
        context = super().get_context_data(**kwargs)  
        context['user_info_form'] = UserInfoForm(instance=self.request.user)  
        context['user_profile_form'] = ProfileForm(instance=self.request.user.profile)  
        context['user_password_form'] = UserPasswordForm(self.request.user)  
        context['title'] = f'Настройки профиля {self.request.user}'  
        return context  

    def post(self, request, *args, **kwargs):  
        if 'user_info_form' in request.POST:  
            user_info_form = UserInfoForm(request.POST, instance=request.user)  
            user_profile_form = ProfileForm(request.POST, request.FILES, instance=self.request.user.profile)  
            if user_info_form.is_valid() and user_profile_form.is_valid():  
                user_info_form.save()  
                user_profile_form.save()  
                messages.success(request, 'Данные успешно изменены.')  
                return redirect('user_app:user_profile_settings', user_info_form.cleaned_data.get('username'))  
            else:  
                context = self.get_context_data(**kwargs)  
                context['user_info_form'] = user_info_form  
                context['user_profile_form'] = user_profile_form  
                return render(request, self.template_name, context)  
        elif 'user_password_form' in request.POST:  
            form = UserPasswordForm(request.user, request.POST)  
            if form.is_valid():  
                form.save()  
                messages.success(request, 'Пароль успешно изменён.')  
                return self.get(request, *args, **kwargs)  
            else:  
                context = self.get_context_data(**kwargs)  
                context['user_password_form'] = form  
                return render(request, self.template_name, context)  
        else:  
            return self.get(request, *args, **kwargs)

project_tracker/user_app/templates/user_app/login.html
{% extends "movieblog/base.html" %}
{% block content %}
    <div class="content">
        <div class="login-block">
            <span class="name entrance-title">Вход</span>
            <form method="post">
                {% csrf_token %}
                {% if form.non_field_errors %}  
                    <div class="alert alert-danger">  
                        {{ form.non_field_errors }}  
                    </div>  
                {% endif %}
                {% for field in form %}
                    <div class="form-group">
                        <p class="form-label">{{ field.label }}</p>  
                        {% if field.name == 'password' %}
                            <input type="password" id="{{ field.id }}" class="form-control" name="{{ field.name }}" value="">
                        {% else %}
                            <input type="text" id="{{ field.id }}" class="form-control" name="{{ field.name }}" value="">
                        {% endif %}
                    </div>
                {% endfor %} 
                <button type="submit" class="btn search-link link-border">Войти</button>  
            </form>
            <div>
                <span class="micro-text">
                    Забыли пароль? <a href="{% url 'user_app:password_reset' %}" class="micro-text entrance__link link link-item">Сбросить пароль</a>
                </span>
            </div>
        </div>
    </div>
{% endblock content %}

project_tracker/user_app/templates/user_app/logout.html
{% extends 'movieblog/base.html' %}  

{% block content %}  
    <div class="content">
        <div class="form-section container">  
            <div class="title">Вы успешно вышли с сайта</div>  
            <a href="{% url 'user_app:login' %}" class="link-item entrance__link">Войти в личный кабинет снова</a>  
        </div>
    </div>
{% endblock %}

project_tracker/user_app/templates/user_app/password_reset.html
{% extends 'movieblog/base.html' %}
 
{% block content %}
<div class="content">
    <div class="login-block">
        <div class = "container mt-3">
            <div class = "col-6">
                <span class="name entrance-title">Восстановление пароля</span>
                <form method="POST">  
                    {% csrf_token %}  
                    <div class="form-group">
                        {{ form.as_p }}  
                    </div>
                    <button type="submit" class="btn btn-outline-success link-border">Запросить новый пароль</button>  
                </form>
            </div>
        </div> 
    </div>
</div>
{% endblock %}

project_tracker/user_app/templates/user_app/password_reset_complete.html
{% extends 'movieblog/base.html' %}
 
{% block content %}
<div class="content">  
    <h2>Вы успешно обновили пароль</h2>  
    <p>Ваш пароль заменен на новый!</p>  
    <a href="{% url 'user_app:login' %}" class="entrance__link link link-item">Войти</a>   
</div>
{% endblock %}

project_tracker/user_app/templates/user_app/password_reset_confirm.html
{% extends 'movieblog/base.html' %}
 
{% block content %}
<div class="content">
    {div class = "container mt-3"}
        {div class = "col-6"}
            <h1>Восстановление пароля</h1>
            <form method="POST">  
                {% csrf_token %}  
                {{ form.as_p }}  
                <button type="submit" class="btn btn-danger mt-3">Сохранить</button>  
            </form>
        </div>
    </div> 
</div>
{% endblock %}

project_tracker/user_app/templates/user_app/password_reset_done.html
{% extends 'movieblog/base.html' %}
{% load i18n %}
 
{% block content %}
<div class="content">  
    <h2>Ссылка для смены пароля отправлена на вашу почту.</h2>  
</div>
{% endblock %}

project_tracker/user_app/templates/user_app/password_reset_email.html
{% load i18n %}{% autoescape off %}  
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}  

{% translate "Please go to the following page and choose a new password:" %}  
{% block reset_link %}  
{{ protocol }}://{{ domain }}{% url 'user_app:password_reset_confirm' uidb64=uid token=token %}  
{% endblock %}  
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}  

{% translate "Thanks for using our site!" %}  

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}  

{% endautoescape %}

project_tracker/user_app/templates/user_app/profile_page.html
{% extends 'movieblog/base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="movie-content">
        <div class="profile">
            <div class="profile-left">
                <h3 class="info">Информация:</h3>
                <img class="profile-avatar" src="{{ user_profile.profile.user_avatar.url }}" alt="{{ user_profile }}" width="300"
                    height="300" class="img-fluid"><br>
                {% for group in user_profile.groups.all %}
                    <span class="badge border mt-3 lead">{{ group.name }}</span>
                {% endfor %}
            </div>
            <div class="profile-right">
                <div>
                    <b>Имя пользователя:</b> {{ user_profile }}
                </div>
                <hr class="">
                {% if user_profile.first_name %}
                    <div>
                        <b>Имя:</b> {{ user_profile.first_name }}
                    </div>
                {% endif %}
                {% if user_profile.last_name and user_profile.profile.show_last_name %}
                    <div>
                        <b>Фамилия:</b> {{ user_profile.last_name }}
                    </div>
                {% endif %}
                <div class="bottom-settings">
                    <b>Пол:</b> {{ user_profile.profile.get_gender_display }}
                </div>
                {% if user_profile.profile.dob %}
                    <div>
                        <b>Возраст:</b> {{ user_profile.profile.get_age }}
                    </div>
                {% endif %}
                <div>
                    <b>На сайте:</b> {{ user_profile.profile.get_on_site }}
                </div>
                <hr class="mb-0">
                {% if user_profile.profile.show_email %}
                    <div>
                        <b>Email:</b> {{ user_profile.email }}
                    </div>
                {% endif %}
                {% if user_profile.profile.show_telegram %}
                    <div>
                        <b>Ссылка на Telegram:</b> <a
                        href="{{ user_profile.profile.telegram_link }}">{{ user_profile.profile.get_telegram_username }}</a>
                    </div>
                {% endif %}
                {% if user_profile.profile.site_link %}
                    <div>
                        <b>Личный сайт:</b> {{ user_profile.profile.site_link }}
                    </div>
                {% endif %}
                {% if user_profile %}
                    <a class="entrance__link link link-item bottom-settings"
                    href="{% url 'user_app:user_profile_settings' username=user_profile.username %}">Настройки
                        профиля</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

project_tracker/user_app/templates/user_app/profile_settings_page.html
{% extends 'movieblog/base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="content">
    <div class="">
        <div class="">
            <h2>Настройки профиля {{ user }}</h2>
        </div>
    </div>
    <hr>
    <br>
    <div>
        <div>
            {% if messages %}
                <p class="alert alert-success">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </p>
            {% endif %}
        </div>
        <div>
            <form method="post" enctype="multipart/form-data">
                <div class="row">
                    <div>
                        <h3>Основная информация:</h3>
                        {% csrf_token %}
                        {% for error in user_info_form.errors.values %}
                            {{ error }}
                        {% endfor %}
                        <br>
                        <div class="settings-block">
                            {{ user_info_form.username.label }}
                            {{ user_info_form.username }}
                        </div>


                        <div class="settings-block">
                            {{ user_info_form.email.label }}
                            <div class="input-group">
                                <div class="input-group-text">
                                    {{ user_profile_form.show_email }}
                                    <span class="ms-2">Отображать?</span>
                                </div>
                                {{ user_info_form.email }}
                            </div>
                        </div>

                        <div class="settings-block">
                            {{ user_info_form.first_name.label }}
                            {{ user_info_form.first_name }}
                        </div>


                        <div class="settings-block">
                            {{ user_info_form.last_name.label }}
                            <div class="input-group">
                                <div class="input-group-text">
                                    {{ user_profile_form.show_last_name }}
                                    <span class="ms-2">Отображать?</span>
                                </div>
                                {{ user_info_form.last_name }}
                            </div>
                        </div>
                    </div>

                    <br>
                    <div>
                        <h3>Дополнительная информация:</h3>
                        <br>
                        {% for error in user_profile_form.errors.values %}
                            {{ error }}
                        {% endfor %}

                        <div class="settings-block">
                            {{ user_profile_form.gender.label }}
                            {{ user_profile_form.gender }}
                        </div>

                        <div class="settings-block">
                            {{ user_profile_form.dob.label }}
                            {{ user_profile_form.dob }}
                        </div>

                        <div class="settings-block">
                            {{ user_profile_form.site_link.label }}
                            {{ user_profile_form.site_link }}
                        </div>
                        <br>
                        <div class="settings-block">
                            {{ user_profile_form.user_avatar.label }}
                            {{ user_profile_form.user_avatar }}<br>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div>
                        <button class="btn search-link link-border" type="submit" name="user_info_form">
                            Отправить
                        </button>
                    </div>
                </div>
                <br>
            </form>
        </div>
        <div>
            <h3>Изменить пароль:</h3>
            <br>
            <form method="post">
                {% csrf_token %}
                <div class="settings-block">
                    {{ user_password_form.as_p }}
                </div>
                <div class="row">
                    <div>
                        <button class="btn search-link link-border" type="submit" name="user_password_form">
                            Отправить
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

project_tracker/user_app/templates/user_app/signup.html
{% extends "movieblog/base.html" %}
{% block content %}
    <div class="content">
        <div class="login-block">
            <span class="name entrance-title">Регистрация</span>
            <form method="post">
                {% csrf_token %}
                {% if form.non_field_errors %}  
                    <div class="alert alert-danger">  
                        {{ form.non_field_errors }}  
                    </div>  
                {% endif %}  
                {% for field in form %}
                    <div class="form-group">
                        <p class="form-label">{{ field.label }}</p>  
                        {% if forloop.counter > 2 %}
                            <input type="password" id="{{ field.id }}" class="form-control" name="{{ field.name }}" value="{{ field.value|default_if_none:'' }}">
                        {% else %}
                            <input type="text" id="{{ field.id }}" class="form-control" name="{{ field.name }}" value="{{ field.value|default_if_none:'' }}">
                        {% endif %}
                        {% if field.errors %}  
                            <ul class="alert alert-danger">  
                                {{ field.errors }}  
                            </ul>  
                        {% endif %}
                    </div>
                {% endfor %} 
                <button type="submit" class="btn btn-outline-success link-border">Зарегистрироваться</button>  
            </form>
        </div>
    </div>
{% endblock content %}